# Jekyll configuration; see https://github.com/mojombo/jekyll/wiki/Configuration
# Note: Jekyll configuration settings may not be respected by GitHub Pages.
# Read the friendly manual: https://help.github.com/articles/using-jekyll-with-pages

baseurl: "/cass24" #"/github-course-starter"  # Replace with name of repo

markdown: kramdown

collections:
  notes:
    output: true
  assignments:
    output: true

defaults:
  -
    scope:
      path: ""  # All files
    values:
      layout: default
